### ISSUE TITLE
--inspect doesn't work when used in NODE_OPTIONS

### ISSUE THREAD

**Issue by daveisfera** [fgnass/node-dev#235]
When running this command: `NODE_OPTIONS="-r esm --inspect=0.0.0.0:9229" node_modules/.bin/node-dev test_inspect.js`

I get this error:
```
Debugger listening on ws://0.0.0.0:9229/f3bc94ca-7c83-4cd3-bc97-60b332ed4f52
For help, see: https://nodejs.org/en/docs/inspector
```

**Comment by bjornstar** [comment]
Is there an error here? That looks like what I would expect to see when using `--inspect`.

**Comment by daveisfera** [comment]
Sorry, forgot to include the 3rd line with the error:
```
Debugger listening on ws://0.0.0.0:9229/10a40133-57a2-4af7-9665-6d6c046acf3e
For help, see: https://nodejs.org/en/docs/inspector
Starting inspector on 0.0.0.0:9229 failed: address already in use
```

**Comment by bjornstar** [comment]
This is expected behavior, `node-dev` is it's own node process that will use NODE_OPTIONS and it will spawn another node process to run your script that will also use NODE_OPTIONS. Both of these processes will try to use the port that you've selected and it will fail as only one process can use the port.

**Comment by bjornstar** [comment]
Any options that aren't for node-dev are passed on to the node process. You should be able to do `node-dev --inspect=0.0.0.0:9229 test_inspect.js`
