### ISSUE TITLE
v8 debugger and node-inspector port conflicts when restarting

### ISSUE THREAD

**Issue by focusaurus** [fgnass/node-dev#80]
So I do two things in my app that seem to have some problems when restarting under node-dev.

1. I run my app with `node-dev --debug=9001 app/server.js`.
1. Within my app, I start node-inspector via
     ` child_process.fork(require.resolve("node-inspector/bin/inspector")...`

Very often when node-dev restarts my server, the new v8 debugger is unable to bind its TCP port and writes this message every second: "Failed to open socket on port 9001, waiting 1000 ms before retrying".

I have also seen a similar error message from `node-inspector`

    warn  - error raised: Error: listen EADDRINUSE
    Cannot start the server at 127.0.0.1:9002. Error: listen EADDRINUSE.
    There is another process already listening at this address.
    Run `node-inspector --web-port={port}` to use a different port.

My guess (just a guess, I could be wrong) is that the initial v8 for whatever reason fails to completely free the TCP port by the time the new one tries to bind it, and it seems once that has happened I must kill node-dev, wait a few seconds, then start again, then all is well.

Is there any way to reliably avoid this issue? I didn't see any available `node-dev` command line options pertinent to this issue. I tried modifying `node-dev` to add a delay before starting the child but that didn't avoid the issue. I also tried adding a delay after my server starts up before starting node-inspector and before starting up the v8 debugger but that also doesn't seem to solve it.

Wondering if there's any reliable way to get everything playing nicely together.

System versions:

* OS X 10.9.1
* node v0.10.24
* node-dev v2.1.6

**Comment by fgnass** [comment]
This should be fixed since 2.2.0 when graceful restarts were introduced. A quick check with the latest node-dev version suggests that they now play together nicely.

**Comment by focusaurus** [comment]
:bow:  thank you!

**Comment by stephenh** [comment]
@fgnass I know it's like 7 years later :-D but curious if you remember what the key approach of graceful restarts was?

I'm trying to get tsx, a new esbuild-based "node but with typescript" (i.e. ts-node), to do the same "run in watch + inspect and don't get 'debugger port in use' errors" that this node-dev issue fixed ([tsx issue here](https://github.com/esbuild-kit/tsx/issues/82)).

You mentioned "this was fixed in 2.2.0", but just scanning the 2.1.0 --> 2.2.0 commits, nothing jumped out at me as the obvious "graceful restarts" commit:

https://github.com/fgnass/node-dev/compare/v2.1.0...v2.2.0

Fwiw the tsx process management code is here:

https://github.com/esbuild-kit/tsx/blob/develop/src/run.ts#L35
https://github.com/esbuild-kit/tsx/blob/develop/src/watch/index.ts#L60

I've tried naively changing `runProcess.kill()` to `runProcess.kill("SIGTERM")`, which I believe is what node-dev does + might have been in the ^ diffs, but it did not magically fix the port in use error.

My only other guess is that tsx is using `spawn`, while node-dev is using `fork`; do you know if this might be the key difference? That `fork` somehow better handles the port-reuse-across-restarts?

Definitely no problem if it's been too long, just thought I'd be lazy and ask if you remembered; if not, I'll probably poke around with `fork` and see if that fixes things.

Thanks!

**Comment by fgnass** [comment]
I think the key change was not to call `process.exit()` in the child process when it receives a SIGTERM if other listeners are registered, so they can do their cleanup. See https://github.com/fgnass/node-dev/commit/ca51b68ae11ccd22fdc52ba340406d6c5414f970#diff-c60d44e47c8429d1d31fd42db19599ed941fe6edc51ea333d97dd639a2e40d49

**Comment by stephenh** [comment]
@fgnass ah wow! Thanks for the response! I've only naively started poking around with `tsx` to see if your insight into `process.exit` behavior is correct, and haven't hit the magic incantation yet, but I'll keep trying as I find time. Thank you!
